var fs = require('fs')

export var newDoc = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/document-new.svg')
export var save = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/document-save.svg')
export var toggle = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/view-fullscreen.svg')
export var cancel = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/edit-undo.svg')
export var destroy = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/edit-delete.svg')
export var attachment = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/mail-attachment.svg')
export var previous = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/go-previous.svg')
export var next = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/go-next.svg')
export var down = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/go-down.svg')
export var bottom = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/go-bottom.svg')
export var first = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/go-first.svg')
export var up = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/go-up.svg')
export var edit = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/edit.svg')
export var online = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/network-transmit-receive.svg')
export var offline = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/network-offline.svg')
export var config = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/applications-system.svg')
export var logout = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/system-log-out.svg')

export var gpsLock = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/ic_gps_fixed.svg')
export var chevronRight = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/ic_chevron_right.svg')
export var chevronLeft = 'data:image/svg+xml;utf8,' + fs.readFileSync(__dirname + '/ic_chevron_left.svg')
export var addPart = 'data:image/png;base64,' + fs.readFileSync(__dirname + '/island-add.png', 'base64')
export var removePart = 'data:image/png;base64,' + fs.readFileSync(__dirname + '/island-delete.png', 'base64')
export var addPoint = 'data:image/png;base64,' + fs.readFileSync(__dirname + '/vertex-create.png', 'base64')
export var zoomGeom = 'data:image/png;base64,' + fs.readFileSync(__dirname + '/zoom-selection.png', 'base64')
